### ISSUE TITLE
Roadmap generador

### ISSUE THREAD

**Issue by alvaromb** [APSL/generator-apsl-angular#1]
Estas son las tareas pendientes para el generador. El orden de prioridad debe ser top-down.
## Bugs
- [x] ~~El watch a los `*.scss` fuera de la carpeta `styles/` no funciona. Se debe modificar el `Gruntfile.js` para que los acepte.~~ (ver https://github.com/APSL/generator-apsl-angular/commit/6db77a1b613b6e94de7cfda095685316a71c0268)
- [ ] `common` debería ir dentro de `app` para que todo funcione correctamente.
- [ ] Al crear un módulo con `yo apsl-generator:module [name]` se añade el controlador como `ControllerCtrl` pero en las rutas se refleja como `[NombreMódulo]Ctrl`.
- [ ] Generar los ficheros html en `[module name]/views/` en lugar de `views/`.
- [ ] Al crear un proyecto, se incluye un js que no se genera: `<script src="scripts/controllers/main.js"></script>`. Parece que viene de la creación del módulo `Main`.
- [ ] Arreglar los tests de controladores y configuración al crear un `module`.
- [ ] Falta añadir `'use strict';` en muchos ficheros auto generados.
## Mejoras
- [x] ~~Documentar instalación básica del generador.~~ (ver https://github.com/APSL/generator-apsl-angular/commit/8c7aa3c375e77984349c18a6dfb290b73c77fe48)
- [x] ~~Eliminar la carpeta `node_modules` y pasar todas las dependencias al `package.json`.~~ (ver https://github.com/APSL/generator-apsl-angular/commit/ba737a814af75e1b4677186d69f3872b9c7299b1)
- [ ] Generar un fichero `.hgignore` con las opciones necesarias. Actualmente generamos un `.gitignore`, se pueden copiar las opciones desde allí.
- [ ] Añadir `grunt-ng-constant` al `package.json` que se genera.
- [ ] Integrar configuración de [angular-gettext](https://angular-gettext.rocketeer.be/dev-guide/) en el generador para apps multi-idioma.
- [ ] Añadir al `watch` los ficheros *`.po` para que ejecute `nggettext_compile` cuando se actualicen.
- [ ] Integrar [font-awesome](https://github.com/FortAwesome/Font-Awesome) en las preguntas de la configuración inicial, igual que con Bootstrap.
- [ ] Integrar [ui-router](https://github.com/angular-ui/ui-router).
- [ ] Añadir la opción de crear una directiva en un módulo concreto de la aplicación. Debe incluir automáticamente los ficheros en el `index.html` y crear tanto el `*.html` como el `*.js` de la directiva.
- [ ] Integrar algún linter.
- [ ] Integrar [Babel](https://babeljs.io).
- [ ] Pasar de `autoprefixer` a `postcss` como el generador de yeoman.

**Comment by alvaromb** [comment]
@franm empieza a haber un volquete de curro importante. Cómo podríamos organizar las tareas que tenemos pendientes? :godmode:

**Comment by alvaromb** [comment]
https://github.com/APSL/generator-apsl-angular/commit/6db77a1b613b6e94de7cfda095685316a71c0268 arregla el problema del `watch` a los `.scss` y copia todos los templates `html` al compilar.
